# Generated by Django 3.2.9 on 2021-12-01 19:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAISitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
                ('published', models.BooleanField(blank=True, default=True, help_text='checking this ON will make the page visible')),
                ('slug', models.SlugField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OAISitePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('content', models.TextField(blank=True)),
                ('featured', models.BooleanField(blank=True, default=False)),
                ('featured_rank', models.IntegerField(blank=True, default=0, help_text='higher numbers are ranked before lower numbers')),
                ('published', models.BooleanField(blank=True, default=True, help_text='checking this ON will make the page visible')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
