# Generated by Django 3.2.9 on 2021-12-02 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaisite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oaisitepage',
            name='published',
            field=models.BooleanField(blank=True, default=True, help_text='Checking this ON will make the page visible'),
        ),
        migrations.AlterField(
            model_name='oaisitepost',
            name='featured_rank',
            field=models.IntegerField(blank=True, default=0, help_text='If featured is checked ON, higher numbers are displayed before lower numbers'),
        ),
        migrations.AlterField(
            model_name='oaisitepost',
            name='published',
            field=models.BooleanField(blank=True, default=True, help_text='Checking this ON will make the post visible'),
        ),
    ]
