# Generated by Django 3.2.9 on 2021-12-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaisite', '0002_auto_20211202_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='oaisitepost',
            name='slug',
            field=models.SlugField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='oaisitepost',
            name='title',
            field=models.CharField(max_length=512),
        ),
    ]
