# Generated by Django 3.2.9 on 2021-12-13 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaisite', '0003_auto_20211213_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oaisitepost',
            name='slug',
        ),
    ]
