# Generated by Django 3.2.9 on 2022-06-25 00:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0007_alter_record_options'),
        ('oaisite', '0004_remove_oaisitepost_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAISiteSupplementaryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(help_text='Enter a display title for this collection.', max_length=512)),
                ('collection_type', models.CharField(help_text='Enter a short string to indicate the type of items in this collection (E.g., podcasts, media, reports)', max_length=512)),
                ('slug', models.SlugField(blank=True, max_length=1024, null=True)),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oaiharvests.collection')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
