# Generated by Django 3.2.9 on 2024-08-28 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaisite', '0006_oaisitepost_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oaisitepost',
            name='post_type',
            field=models.CharField(choices=[('', ''), ('Call for Proposals', 'Call for Proposals'), ('Call for Papers', 'Call for Papers'), ('Call for Volunteers', 'Call for Volunteers'), ('Awards', 'Awards')], default='', max_length=48),
        ),
    ]
