# Generated by Django 3.2.9 on 2024-08-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaisite', '0008_alter_oaisitepost_post_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oaisitepost',
            old_name='post_type',
            new_name='post_tag',
        ),
    ]
