# Generated by Django 3.2.9 on 2021-12-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='edited_by',
            field=models.TextField(blank=True, default='', help_text='Enter editor names (first then last). Separate multiple editor names with a comma.'),
        ),
    ]
