# Generated by Django 3.2.9 on 2021-12-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0002_collection_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Provide a short description of this collection.'),
        ),
    ]
