# Generated by Django 3.2.9 on 2022-01-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0003_collection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='is_special_issue',
            field=models.BooleanField(default=False, help_text='Check on to indicate that this is a Special Issue'),
        ),
    ]
