# Generated by Django 3.2.9 on 2022-01-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0004_collection_is_special_issue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='is_special_issue',
            new_name='special_issue',
        ),
    ]
