# Generated by Django 3.2.9 on 2022-02-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0005_rename_is_special_issue_collection_special_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
