# Generated by Django 3.2.9 on 2022-06-25 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oaiharvests', '0006_record_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['-hdr_datestamp']},
        ),
    ]
